### ISSUE TITLE
[FEATURE] seedfarmer plan option

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#158]
**Is your feature request related to a problem? Please describe.**
I would like to have a way to inspect the changes of the modules before applying. Equivalent of cdk diff or terraform plan.
Right now, to inspect the changes I have to mock inputs to the module and run cdk diff which is rather cumbersome.

**Describe the solution you'd like**
I would like to have an option like:
`seedfarmer plan` or `seedfarmer diff`, which would work similarly to `seedfarmer apply` but run `plan` from `deployspec.yaml` and report output.

For example:
```
# --- typical deployspec --- 
deploy:
  phases:
    install:
      commands:
      # Install whatever additional build libraries
      - npm install -g aws-cdk@2.20.0
      - pip install -r requirements.txt
    build:
      commands:
      # execute the CDK
      - cdk deploy --require-approval never --progress events --app "python app.py" --outputs-file ./cdk-exports.json
      # derive the metadata environment parameter name that seedfarmer is looking for from the CODESEEDER project name
      - export P_METADATA=$(echo $AWS_CODESEEDER_NAME | tr '[:lower:]' '[:upper:]')_MODULE_METADATA
      # assign that paramter name the output from CDK by calling a custom python script
      - export ${P_METADATA}=$(python export_metadata.py)
destroy:
  phases:
    install:
      commands:
      # Install whatever additional build libraries
      - npm install -g aws-cdk@2.20.0
      - pip install -r requirements.txt
    build:
      commands:
      # execute the CDK
      - cdk destroy --force --app "python app.py"
 
# --- proposed addition ---
# add option to execute below commands when running seedfarmer plan
plan:
  phases:
    install:
      commands:
      - npm install -g aws-cdk@2.46.0
      - pip install -r requirements.txt
    build:
      commands:
      - cdk diff --app "python app.py"

```
I would expect that now if I run `seedfarmer plan` I would get the output of `build` part of `plan` from `deployspec.yaml` in the console.

**Describe alternatives you've considered**
Mocking the inputs and running the cdk diff.
