### ISSUE TITLE
[FEATURE] Load DeploymentName from `.env`

### ISSUE THREAD

**Issue by srinivasreddych** [awslabs/seed-farmer#169]
**Is your feature request related to a problem? Please describe.**
With the introduction of `.env` in 2.2.0 release, we are able to cut down the manifest files by a great % but we still need a deployment.yaml file per developer, because we cant load `deployment_name` from `.env`

**Describe the solution you'd like**
Being able to declare `deployment_name` from `.env`
```yaml
name: 
     valueFrom:
      envVariable: DEPLOYMENT_NAME
toolchainRegion: us-west-2
groups:
  - name: optionals
    path: manifests/optional-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId: 1234567890
    default: true
    regionMappings:
      - region: us-west-2
        default: true
```

**Describe alternatives you've considered**
We are currently creating a deployment.yaml per developer and running seedfarmer apply commands against a developer specific file.

**Additional context**

**Comment by kevinsoucy** [comment]
+1

**Comment by AndyEfaa** [comment]
+ 1 
Ideally, we have this option on the deployment name, group name and module name definition.
Deployment name is the most important one. 
The others will be helpful if you only want certain parts of the deployment to be "dynamic" in regards to naming.

**Comment by chamcca** [comment]
I'm hesitant to implement this.. the suggested implementation potentially makes the `name` of a deployment non-deterministic in any way. looking at 
```
name:
  valueFrom:
    envVariable: DEPLOYMENT_NAME
```
in the manifest doesn't give any indication of what the actual deployment name is. I assume the env file would look something like
```
DEPLOYMENT_NAME=developer-${USER}
```
giving a unique deployment for each developer in a shared account.

my concern with this is it makes any identification of the deployment difficult.

an alternative approach would be to take an idea from kubernetes and their `generateName` attribute. on a Pod or other resource you have the option of using either a static `name` or a dynamic `generateName` where you define a naming convention.

what if we did something similar, enabling definition of a static `name` or a `nameGenerator`, where the generator could take the form 
```
nameGenerator:
  prefix: developer-
  suffix: 
    valueFrom:
      envVariable: USER
```
this would also allow us to use auto generated suffixes like
```
nameGenerator:
  prefix: developer-
  suffix:
    valueFrom:
      autoDigits: 6
```
where `autoDigits` would append 6 automatically generated alphanumeric digits.

in this way we could also support `valueFrom` on the `prefix` as well. 

what I prefer here is that an admin can glance at the deployment manifest file and at least determine the set of deployments it applies to in a shared environment.
