### ISSUE TITLE
[FEATURE] Refactor seedfarmer to accept `networking` from manifest and flow it through metadata

### ISSUE THREAD

**Issue by dgraeber** [awslabs/seed-farmer#227]
To launch workloads in isolated env, the idea is to accept `networking` details from the deployment.yaml file and make it available to be referenced inside an application specific manifest file.

future `deployment.yaml` file would look like:
```
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: GLOBAL_AWS_ACCOUNTID_APPLICATION
    default: true
    parametersGlobal:
      dockerCredentialsSecret: aws-addf-docker-credentials
    regionMappings:
      - region: eu-central-1
        default: true
      # networking: 
        #   vpc: 
        #   subnets:["", ""]
        #   sgs: 
```

and the application manifest would grab the networking details using:
```
parameters:
  - name: vpc-id
    valueFrom: regionVpc
```
