### ISSUE TITLE
[FEATURE] Array of ValueFrom in module-manifests

### ISSUE THREAD

**Issue by PatWie** [awslabs/seed-farmer#247]
**Is your feature request related to a problem? Please describe.**
Having a module that creates a AWS Fargate Task (concrete example is for [aws-batch](https://github.com/awslabs/autonomous-driving-data-framework/tree/main/modules/core/aws-batch)) might require some policies attached to the JobRole. For example, for reading and writing data from the Fargate Task a module manifest would look like

```yaml
name: task-a
path: modules/compute-jobs/fargate/
parameters:
  - name: fargate-job-queue-arn
    valueFrom:
      moduleMetadata:
        group: core
        name: batch-compute
        key: FargateJobQueueArn
  - name: input-read-policy-arn
    valueFrom:
      moduleMetadata:
        group: datalake
        name: input-store
        key: ReadOnlyAccessPolicyArn
  - name: output-write-policy-arn
    valueFrom:
      moduleMetadata:
        group: datalake
        name: output-store
        key: FullAccessPolicyArn
``` 

assuming the stack is aware of `<PREFIX>_PARAMETERS_INPUT_READ_POLICY` and `<PREFIX>_PARAMETERS_OUTPUT_WRITE_POLICY`. It is not possible to have a dynamic length of such parameters. For hard-coded strings the following works:

```yaml
parameters:
  - name: fargate-job-queue-arn
    value: "my-queue-arn"
  - name: policies-to-attach
    value: 
         - name: policy-a-arn
            value: "arn-of-policy-a"
         - name: policy-b-arn
            value: "arn-of-policy-b"
         - name: policy-c-arn
            value: "arn-of-policy-c"
```

as it is passed to stack ([example](https://github.com/awslabs/autonomous-driving-data-framework/blob/main/modules/core/aws-batch/stack.py#L117)). But for value-references as described [in the documentation](https://seed-farmer.readthedocs.io/en/latest/manifests.html#modulemetadata) this is not possible.

**Describe the solution you'd like**
It would great of the configuration can look like

```yaml
parameters:
  - name: fargate-job-queue-arn
    value: "my-queue-arn"
  - name: policies-to-attach
    value: 
         - name: policy-a-arn
            valueFrom: ...
         - name: policy-b-arn
            valueFrom: ...
         - name: policy-c-arn
            valueFrom ...
```
with unknown number of policies in `<PREFIX>_PARAMETERS_POLICIES_TO_ATTACH` and 
correctly replaced with the retrieved values from the META-DATA (Currently, those `valueFrom` do not get substituted with the actual values). Ideally, there would be a pass over the module configuration in a post-order traversal fashion and substitute all value-references.

**Describe alternatives you've considered**
A workaround is to write

```yaml
name: task-a
path: modules/compute-jobs/fargate/
parameters:
  - name: policy-arn-string-or-empty-1
    valueFrom: ...
  - name: policy-arn-string-or-empty-2
    valueFrom: ...
  - name: policy-arn-string-or-empty-3
    valueFrom: ...
  - name: policy-arn-string-or-empty-4
    valueFrom: ...
  - name: policy-arn-string-or-empty-5
    valueFrom: ...
``` 

for a certain capacity (here 5) and skip empty strings in the stack definition. However, it requires the amount of policies to be known in advance.

**Comment by dgraeber** [comment]
```
parameters:
  - name: fargate-job-queue-arn
    value: "my-queue-arn"
  - name: policies-to-attach
    value: 
         - name: policy-a-arn
            valueFrom: ...
         - name: policy-b-arn
            valueFrom: ...
         - name: policy-c-arn
            valueFrom ...
```
Is not a viable proposal as there is no key word to indicate that an array is presented with the need for seed-farmer substitution.  We can explore other possibilities to determine feasibility ... PERHAPS something along the lines of:

```
parameters:
  - name: fargate-job-queue-arn
    value: "my-queue-arn"
  - name: policies-to-attach
    valueArray: 
         - name: policy-a-arn
            valueFrom: ...
         - name: policy-b-arn
            valueFrom: ...
         - name: policy-c-arn
            valueFrom ...
```
I am speculating at the moment about the above.
There will most likely be limitations...the most pronounced is that the array contents will be strings 


More to come
