### ISSUE TITLE
[BUG] `False` boolean doesnt get resolved.

### ISSUE THREAD

**Issue by srinivasreddych** [awslabs/seed-farmer#280]
**Describe the bug**
If a parameter value is set to `False` or `false`, the value doesn't get resolved/picked in SEEDFARMER environment variables. 

**To Reproduce**
```yaml
name: basic-networking
path: modules/network/basic-cdk/
parameters:
  - name: internet-accessible
    value: false
```

**Expected behavior**
Expect to see `SEEDFARMER_PARAMETER_INTERNET_ACCESSIBLE` value set to the right value from manifest entry

**Screenshots**

**Additional context**
