### ISSUE TITLE
[BUG] Seedfarmer boostrap toolchain --as-target synth output is missing deployment role

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#307]
**Describe the bug**
The seedfarmer command bootstrap toolchain --project addf -t TRUSTED-PRINCIPAL-ARN --as-target --synth is only outputting the toolchain policy, instead of outputting two CloudFormation templates, one for the toolchain and one for the target.

**To Reproduce**
    Run the seedfarmer command bootstrap toolchain --project addf -t TRUSTED-PRINCIPAL-ARN --as-target --synth
    Check the output. It will be:
```
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation for the SeedFarmer Toolchain Role
Outputs:
  ToolchainRoleName:
    Value:
      Ref: ToolchainRole
Resources:
  ToolchainRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            AWS:
            - TRUSTED-PRINCIPAL-ARN
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - sts:AssumeRole
            - sts:TagSession
            - sts:GetSessionToken
            Effect: Allow
            Resource:
            - arn:aws:iam::*:role/seedfarmer-addf*
            Sid: ToolChainSTS
          - Action:
            - ssm:Put*
            - ssm:Delete*
            - ssm:Remove*
            - ssm:Add*
            - ssm:Describe*
            - ssm:Get*
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:ssm:*:${AWS::AccountId}:parameter/addf/*
            Sid: ToolChainSSM
          - Action:
            - ssm:Describe*
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:ssm:*:${AWS::AccountId}:*
        PolicyName: InlineToolchain
      RoleName: seedfarmer-addf-toolchain-role
    Type: AWS::IAM::Role
```
**Expected behavior**
The seedfarmer command bootstrap toolchain --project addf -t TRUSTED-PRINCIPAL-ARN --as-target --synth should output two CloudFormation templates, one for the toolchain and one for the target, along with the toolchain policy.
```
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation for the SeedFarmer Toolchain Role
Outputs:
  ToolchainRoleName:
    Value:
      Ref: ToolchainRole
Resources:
  ToolchainRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            AWS:
            - TRUSTED-PRINCIPAL-ARN
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - sts:AssumeRole
            - sts:TagSession
            - sts:GetSessionToken
            Effect: Allow
            Resource:
            - arn:aws:iam::*:role/seedfarmer-addf*
            Sid: ToolChainSTS
          - Action:
            - ssm:Put*
            - ssm:Delete*
            - ssm:Remove*
            - ssm:Add*
            - ssm:Describe*
            - ssm:Get*
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:ssm:*:${AWS::AccountId}:parameter/addf/*
            Sid: ToolChainSSM
          - Action:
            - ssm:Describe*
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:ssm:*:${AWS::AccountId}:*
        PolicyName: InlineToolchain
      RoleName: seedfarmer-addf-toolchain-role
    Type: AWS::IAM::Role
```
and 

```
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation for the SeedFarmer Deployment Role
Outputs:
  DeploymentRoleName:
    Value:
      Ref: DeploymentRole
Resources:
  DeploymentRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::TOOLCHAIN-ACCOUNT-ID:role/seedfarmer-addf-toolchain-role
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - kms:Get*
            - kms:Decrypt
            - kms:Untag*
            - kms:Put*
            - kms:List*
            - kms:Tag*
            - kms:Encrypt
            - kms:Describe*
            - kms:Update*
            - kms:Delete*
            - kms:Create*
            Effect: Allow
            Resource:
            - Fn::Sub: arn:aws:kms:*:${AWS::AccountId}:alias/codeseeder-addf-*
            Sid: DeploymentKMSAlias
          - Action:
            - kms:ListKeys
            - kms:UpdateCustomKeyStore
            - kms:ListAliases
            - kms:CreateKey
            - kms:PutKeyPolicy
            - kms:Tag*
            - kms:Untag*
            - kms:ScheduleKey*
            - kms:DescribeKey
            - kms:CreateAlias
            - kms:DeleteAlias
            Effect: Allow
            Resource: '*'
            Sid: DeploymentKMSKey
          - Action:
            - iam:Delete*
            - iam:Create*
            - iam:Get*
            - iam:Tag*
            - iam:Untag*
            - iam:Update*
            - iam:AttachRolePolicy
            - iam:PutRolePolicy
            - iam:Pass*
            - iam:DetachRolePolicy
            - iam:List*
            Effect: Allow
            Resource:
            - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/addf-*
            - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/codeseeder-addf-*
            - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/addf-*
            - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/codeseeder-addf-*
            Sid: DeploymentIAM
          - Action:
            - codebuild:Update*
            - codebuild:Batch*
            - codebuild:Create*
            - codebuild:Delete*
            - codebuild:StartBuild
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:codebuild:*:${AWS::AccountId}:project/codeseeder-addf*
            Sid: DeploymentCodeBuild
          - Action:
            - iam:ListPolicies
            - ssm:DescribeParameters
            - secretsmanager:ListSecretVersionIds
            - codebuild:ListProjects
            - cloudformation:Describe*
            - cloudformation:GetTemplate
            Effect: Allow
            Resource: '*'
            Sid: DeploymentListStuff
          - Action:
            - cloudformation:*
            Effect: Allow
            Resource:
            - Fn::Sub: arn:aws:cloudformation:*:${AWS::AccountId}:stack/addf-*
            - Fn::Sub: arn:aws:cloudformation:*:${AWS::AccountId}:stack/aws-codeseeder-addf/*
          - Action:
            - s3:Delete*
            - s3:Put*
            - s3:Get*
            - s3:Restore*
            - s3:Create*
            - s3:List*
            Effect: Allow
            Resource:
            - arn:aws:s3:::codeseeder-addf*
            - arn:aws:s3:::codeseeder-addf*/*
            Sid: DeploymentS3
          - Action:
            - sts:AssumeRole
            - sts:TagSession
            - sts:GetSessionToken
            Effect: Allow
            Resource:
            - arn:aws:iam::*:role/addf-*
            Sid: DeploymentSTS
          - Action:
            - ssm:Put*
            - ssm:Delete*
            - ssm:Remove*
            - ssm:Add*
            - ssm:Describe*
            - ssm:Get*
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:ssm:*:${AWS::AccountId}:parameter/addf/*
          - Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:GetLogEvents
            - logs:GetLogRecord
            - logs:GetLogGroupFields
            - logs:GetQueryResults
            - logs:DescribeLogStreams
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/codebuild/codeseeder-addf*
          - Action:
            - cloudformation:Create*
            - cloudformation:Execute*
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:cloudformation:*:${AWS::AccountId}:stack/aws-codeseeder-addf*/*
          - Action:
            - codeartifact:*
            Effect: Allow
            Resource:
            - Fn::Sub: arn:aws:codeartifact:*:${AWS::AccountId}:domain/aws-codeseeder-addf
            - Fn::Sub: arn:aws:codeartifact:*:${AWS::AccountId}:repository/aws-codeseeder-addf*
        PolicyName: InlineToolchain
      RoleName: seedfarmer-addf-deployment-role
    Type: AWS::IAM::Role
```

**Screenshots**

**Additional context**
