### ISSUE TITLE
[FEATURE] Raise errors when params do not exists

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#355]
**Is your feature request related to a problem? Please describe.**
I would like to request a feature that raises an error when a parameter does not exist but it is referenced, instead of allowing the program to proceed. This leads to very confusing errors.

**Describe the solution you'd like**
I would like Seedfarmer to raise an error when a parameter that does not exist is passed as an argument.

**Describe alternatives you've considered**
I have considered manually checking for the existence of parameters before using them, but this leads to very repetitive work.

**Additional context**
Example:
```  
name: app
path: modules/web-app/app/
parameters:
  - name: eks-cluster-name
    valueFrom:
      moduleMetadata:
        group: eks
        name: eks
        key: EksClusterName
```  
If the EksClusterName key or eks module or eks group does not exsits, no error is raised. 
Ive observed similar issue with SSM parameters. Not sure about env vars.
