### ISSUE TITLE
[FEATURE] Introduce Parallelism Control for CodeBuild Jobs in SeedFarmer Deployment

### ISSUE THREAD

**Issue by zaremb** [awslabs/seed-farmer#411]
**Is your feature request related to a problem? Please describe.**
I'm facing challenges when using SeedFarmer to deploy modules, as it deploys all modules within one group in parallel, potentially exceeding the service limits for CodeBuild jobs in my AWS account.

**Describe the solution you'd like**
Add a "-parallelism=n" parameter to SeedFarmer, allowing users to set the maximum concurrent executions of CodeBuild jobs during deployment. (Similarly to https://developer.hashicorp.com/terraform/cli/commands/apply#parallelism-n )

**Describe alternatives you've considered**
Managing concurrent jobs by moving modules to different groups - that would result in illogical split of modules. Raising service limits - I would like to, however in my case I am not allowed to.

**Comment by dgraeber** [comment]
@zaremb This is actually already implemented.  By default, we deploy all modules in the group in parallel (with the number of parallel threads being equal to the number of modules in the group).  But we also support limiting the number of concurrent/parallel threads in the group.  For example, the following snippet of a deployment manifest:

```
name: addf-demo
toolchainRegion: us-east-1
groups:
  - name: optionals
    path: manifests/addf-demo/optional-modules.yaml
    concurrency: 2
  - name: core
    path: manifests/addf-demo/core-modules.yaml
    concurrency: 2
```

Here, the concurrency of each group is limited to `2`.   

Unfortunately, this is not documented - so that is a bug.  I will create a new bug to address the docs....and will leave this issue open for you to reply / acknowledge.
