### ISSUE TITLE
[BUG] Document concurency support for groups

### ISSUE THREAD

**Issue by dgraeber** [awslabs/seed-farmer#412]
The Seef-Farmer CLI supports throttling the concurrent codebuild jobs in a group, but the docs do not reflect this support.  Please add this to the documentation.  For example the following deplyment.yaml manifest is valid:

```
name: addf-demo
toolchainRegion: us-east-1
groups:
  - name: optionals
    path: manifests/addf-demo/optional-modules.yaml
    concurrency: 2
  - name: core
    path: manifests/addf-demo/core-modules.yaml
    concurrency: 2
```
Please document this `concurrency` attribute
