### ISSUE TITLE
[BUG] Schema validation for manifest metadata references

### ISSUE THREAD

**Issue by 3sztof** [awslabs/seed-farmer#531]
Seedfarmer doesn't seem to validate the schema of the module metadata references (and possibly other fields).
Submitting this as a bug, as I believe some validations are already in place - perhaps they just need to be stricter.

**To Reproduce**
1. Make a syntax error in the module parameter referencing other module's metadata (for instance remove the `valueFrom:` line)
2. Deploy the module

Example:
```yaml
name: module-name
path: module-folder/module.yaml
parameters:
  - name: PARAMETER
      moduleMetadata:
        group: param-group
        name: param-name
        key: param-key
```
👆 Notice the missing `valueFrom:` line and indentation

**Expected behavior**
Seedfarmer should validate (with [Pydantic](https://docs.pydantic.dev/latest/)?) the schema prior to deployment, crash and print an explicit error message.

**Additional context**
In my faulty configuration, Seedfarmer deployed all of the modules and crashed with module-internal validations (received "None" instead of a value from an env var that was expected to be set by Seedfarmer). The expected environment variable was not created at all in Codebuild - thus it could not be read by the module's code.

This behaviour can be extremely hard to debug and catch (the user has to dive deep on how Seedfarmer handles cross-module metadata and go line-by-line through the configuration.
