### ISSUE TITLE
[FEATURE] Dynamic name of SSM parameter in deployment manifest

### ISSUE THREAD

**Issue by smarkus577** [awslabs/seed-farmer#562]
**Is your feature request related to a problem? Please describe.**
Currently, the name of the parameter to be read from the parameter store must be hard-coded in the deployment manifest in order to verify if the parameter has changed. In our project, we make use of several namespaces to generate isolated development environments. Consequently, we have isolated parameters for each namespace. Therefore, the name of the parameter contains the namespace. As a result, the name of the parameter has to be manually changed for each deployment.
e.g. `/project/<namespace>/parameter`

**Describe the solution you'd like**
It would be great if the name of the parameter could be generated dynamically. For example, it could be templated from an environment variable and/or by using a `suffix` like in the nameGenerator feature.

**Describe alternatives you've considered**
We considered reading the parameter in the stack, but with this approach, a change of the parameter isn't detected and the deployment of the module is skipped

**Comment by dgraeber** [comment]
@smarkus577 Thanks for your request.  Can you provide a sample manifest snippet so I am clear as to what parameter you are interested in.   We typically do not dynamically generate parameter names due to dependency needs and our preference to be declarative.  The deployment name is unique in that no module actually references it directly...

**Comment by dgraeber** [comment]
@smarkus577 Thanks....we are reviewing...

**Comment by dgraeber** [comment]
We can implement this request @smarkus577 .

**Comment by dgraeber** [comment]
@smarkus577 @a13zen I published 3.5.0rc1 to pypi.  Can you give it a try with these latest changes?  This implements the use of `${ } ` for environment replacement:

```
name: dummy-method
path: modules/dummy_product
parameters:
  - name: account-id
    valueFrom:
        envVariable: REALM_ACCOUNT_ID
  - name: namespace
    valueFrom:
      envVariable: NAMESPACE
  - name: common-layer-arn
    valueFrom:
      parameterStore: /addf/rff/${NAMESPACE}/common-layer/arn
```

**Comment by a13zen** [comment]
Nice 💪

**Comment by smarkus577** [comment]
@dgraeber Thanks! Works 💪

**Comment by dgraeber** [comment]
@smarkus577 use rc2.....it has the additional recursion for lists (outside chance of using t, but it is there)

**Comment by smarkus577** [comment]
@dgraeber Can you please check if the `valueFrom -> parameterValue` functionality is still working with the 3.5.0rc1/2? 
My deployment failed with 
> seedfarmer.errors.seedfarmer_errors.InvalidManifestError: The parameter value defined (methodName) is not available

```
  - name: method-name
    valueFrom:
      parameterValue: methodName
```

```
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: REALM_ACCOUNT_ID
    default: true
    parametersGlobal:
      methodName: dummy
```
