### ISSUE TITLE
[FEATURE] Support Cross-Deployment Metadata Sharing

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#668]
**Is your feature request related to a problem? Please describe.**
Support metadata export/import across deployments. If users can import/export metadata across deployments, they can have shared resources such as EKS/Airflow/Buckets etc that don't need to be namespace specific in one deployment, and then they can import and use the shared resources in their namespace deployment. 

This would also allow reducing the overall Role footprint as users don't need to deploy copies of the shared resources. It would also allow reducing costs while still supporting namespaces.

**Describe the solution you'd like**
- Support importing metadata across seedfarmer deployments etc.

```yaml
  - name: EKS_CLUSTER_NAME
    valueFrom:
      moduleMetadata:
        deployment: "shared-eks-cluster" <----- NEW
        group: eks
        name: shared-cluster
        key: ClusterName
```

Dependency management can be completely manual. If the target entry in SSM doesn't exist. FAIL the deployment of the module depending on it (can be checked during validation). If the value in SSM is garbage, or out of date, that is up to the end user to ensure they deploy dependencies in the correct order.
