### ISSUE TITLE
[FEATURE] Support referencing modules via git urls

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#90]
**Is your feature request related to a problem? Please describe.**
Multiple teams using seed-farmer as the deployment mechanism would require a way to reuse modules from each other across different git repositories. 

**Describe the solution you'd like**
Allow referencing modules via git urls including version/commit hash pegging. For example, see how terraform does this (https://www.terraform.io/language/modules/sources#github)

Allow specifying the module path as a git URL in the manifest:

```yaml
name: networking
path: git::https://example.com/network.git//modules/vpc?ref=v1.2.0
parameters:
  - name: internet-accessible
    value: true
---
name: buckets
path: modules/optionals/buckets
parameters:
  - name: encryption-type
    value: SSE
```

**Describe alternatives you've considered**
Git subtrees can be used to get around this, although it bloats the code and adds much more complexity.

**Comment by chamcca** [comment]
# Proposal

rather than reusing the `path` attribute to reference either a local or git path, propose instead we add an optional `git` attribute to the Module Manifest
```
name: networking
path: git-modules/network/modules/vpc
git: 
  repository: https://example.com/network.git
  branch: v1.2.0
parameters:
  - name: internet-accessible
    value: true
```
on `seedfarmer apply` the bundling and deployment of modules will:
1. check the local, relative `path` for the module code, if directory exists and is not empty, bundle and deploy the module
2. if the local, relative `path` directory does not exist or is empty, peform a `git clone` of the `repository` into top-most directory referneced in `path` (in this example **git-modules**)
3. reattempt to locate the module code by checking the local, relative `path`. if the directory exists and is not empty, bundle and deploy, else ERR

utilizing this workflow has a few advantages:
- during module development the local, relative `path` will contain the module code being developed and tested. performing `seedfarmer apply` will utilize the local code
- cloning into the top most directory referenced in `path` (here **git-modules**) and locating modules within sub-directories enables the git repository to contain more than one module. the repository will be cloned once when the first module references the directory
- varying versions/branches of the same repository can be used for different modules by adjusting the top most directory, for example:
  ```
  name: networking
  path: git-modules-1/my-repo/modules/networking/vpc
  git: 
    repository: https://example.com/my-repo.git
    branch: v1.2.0
  parameters:
    - name: internet-accessible
      value: true
  ---
  name: buckets
  path: git-modules-2/my-repo/modules/buckets
  git: 
    repository: https://example.com/my-repo.git
    branch: v1.3.0
  parameters:
    - name: encryption-type
      value: SSE
  ```
